version: '3.7'

services:
  web:
    build:
      context: ../app
      dockerfile: Dockerfile
    command: gunicorn crm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=virtuapp
      - POSTGRES_PASSWORD=virtuapass
      - POSTGRES_DB=redenc

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - /data/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: