version: '3.7'

services:  
  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: crmvirtua@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 'virtua@super'
    deploy:
      mode: replicated
      replicas: 1
      placement:
          constraints:
            - node.role == manager
      resources:
          limits:
            cpus: '0.4'
            memory: 256M
      labels:
          - traefik.enable=true
          - traefik.http.routers.pgadmin.rule=Host(`pgadmin.virtuacrm.app`)  #ajustar endereço
          - traefik.http.services.pgadmin.loadbalancer.server.port=80
          - traefik.http.routers.pgadmin.service=pgadmin
          - traefik.http.routers.pgadmin.tls.certresolver=letsencryptresolver
          - traefik.http.routers.pgadmin.entrypoints=websecure
          - traefik.http.routers.pgadmin.tls=true
    networks:
        - rede_virtua

networks:
  rede_virtua:
    name: rede_virtua
    external: true

volumes:
  pgadmin_data:
    external: true