version: '3.7'


##############
#
# Execute o mando para migrar o banco:
#
# python manage.py makemigrations
# python manage.py makemigrations matriculas
# python manage.py migrate
# python manage.py collectstatic
#############

services:
  virtuapp:
    image: crmvirtua/virtuapp:latest 
    command: gunicorn crm.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    environment:
      - DEBUG=0
      - SECRET_KEY=n6sylk*yhwduv4la$2qu+8^og5$m!rvn9&gy#4499r&7e9vb35
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=redenc
      - SQL_USER=virtuapp
      - SQL_PASSWORD=virtuapass
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        # alterar dominio
        - traefik.http.routers.virtuapp.rule=Host(`appnc.virtuacrm.app`) 
        - traefik.http.routers.virtuapp.entrypoints=websecure
        - traefik.http.routers.virtuapp.tls.certresolver=letsencryptresolver
        - traefik.http.routers.virtuapp.priority=1
        - traefik.http.routers.virtuapp.service=virtuapp
        - traefik.http.services.virtuapp.loadbalancer.server.port=3000 
        - traefik.http.services.virtuapp.loadbalancer.passhostheader=true 
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.virtuapp.middlewares=sslheader@docker
volumes:
  static_volume:
    external: true
    name: static_volume

networks:
  rede_virtua:
    external: true
    name: rede_virtua