# Generated by Django 4.2.7 on 2023-12-15 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cad_campanhas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'campanhas',
            },
        ),
        migrations.CreateModel(
            name='cad_cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cursos',
            },
        ),
        migrations.CreateModel(
            name='cad_polos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AP', 'AMAPÁ'), ('AM', 'AMAZONAS'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('DF', 'DISTRITO FEDERAL'), ('ES', 'ESPÍRITO SANTO'), ('GO', 'GOIÁS'), ('MA', 'MARANHÃO'), ('MT', 'MATO GROSSO'), ('MS', 'MATO GROSSO DO SUL'), ('MG', 'MINAS GERAIS'), ('PA', 'PARÁ'), ('PB', 'PARAÍBA'), ('PR', 'PARANÁ'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUÍ'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'RIO GRANDE DO NORTE'), ('RS', 'RIO GRANDE DO SUL'), ('RO', 'RONDÔNIA'), ('RR', 'RORAIMA'), ('SC', 'SANTA CATARINA'), ('SP', 'SÃO PAULO'), ('SE', 'SERGIPE'), ('TO', 'TOCANTINS')], max_length=2)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(related_name='polos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'polos',
            },
        ),
        migrations.CreateModel(
            name='cad_processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(choices=[('51', '51'), ('52', '52'), ('53', '53'), ('54', '54')], max_length=2)),
                ('ano_processo', models.CharField(max_length=4)),
                ('data_inicial_processo', models.DateTimeField()),
                ('data_final_processo', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'processo',
            },
        ),
        migrations.CreateModel(
            name='tipo_curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pontos', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_curso',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('U', 'USUARIO'), ('A', 'ADMINISTRADOR')], max_length=1)),
                ('polo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matriculas.cad_polos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_matricula', models.DateTimeField()),
                ('nome_aluno', models.CharField(max_length=200)),
                ('numero_ra', models.CharField(max_length=12)),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=6)),
                ('desconto_polo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('desconto_total', models.IntegerField()),
                ('pontos_trocados', models.IntegerField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('comprovante', models.ImageField(blank=True, null=True, upload_to='comprovantes/')),
                ('active', models.BooleanField(default=True)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='arquivos_matricula/')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.cad_campanhas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.cad_cursos')),
                ('processo_sel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.cad_processo')),
                ('tipo_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matriculas.tipo_curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matricula',
            },
        ),
        migrations.AddField(
            model_name='cad_cursos',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.tipo_curso'),
        ),
    ]
