# Generated by Django 4.2.7 on 2023-12-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ranking',
            field=models.BooleanField(default=True),
        ),
    ]
