# Generated by Django 4.2.7 on 2023-12-22 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0002_userprofile_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cad_cursos',
            name='tipo_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.tipo_curso'),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='campanha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.cad_campanhas'),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.cad_cursos'),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='processo_sel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matriculas.cad_processo'),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='tipo_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='matriculas.tipo_curso'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
